#include<stdio.h>
#include "WT.h"
#include"LC.h"



int main()
{

    //char seq[] = "TCGACCAAGCTGGTTTTTCCGTCCTGCCTTTTCCGATAGAGCGATCCTTTGACTGACTAAGGAGCCGGTAGCGATATACCTAGTATTGCGCGCGTCTCGGAGGGCGAGGCTAGATTTAAACGGGTCCGATTTCGGCCAGCTAAGGATTTGATTAAAAAATGTTTCCCGATCCCAACCATAGGGACTTGGTCTTCCAAAACTAATGACACATGTGAATACAAGATGGATGGAGTGATCCCCATTCGAGCGACGCTGATAGCCTAAGCTGCTCCTGATGCGCCGTTTACTTTGAACTAAGGT";    
    char seq[5][301]={
                "CAGTTAGCCCTAATGCCTCCGGGGTTGTGAAAAGTTTAACCACAATTTGCTGGCTTGGGTTACACCATAGATTTAGACCACTCACCTGATTTTGGGTGAGCGATATGCGTGTGTGTTATGGGAGTAGATTGAATCTCATAGTCTGATACAAGAACTCCCTTCTACATCGCTTGATTTAAGGTTGTTACCCTGACCTGGCATGGCGCGGAGACGAGACGAACTGGGGAGAGATTGTCAAAAGTGAGGGTACGCTGCAGGTAGGTTTTAACATGAGCGAACTTGGACATCTAGACGGGAACG",
                "TTCCACTTGGAGCAACCCGAACACGTGTACAGACATAACTATCGATCTATGCCCGGTATCTGGGGATGGCTCAATGCGCGAGACTACTTTTAAAGCGGCATAACTCTTGAGAAGCTCCTTCTACAGTGCCCGCTGCCTGCGTGCTCCCCACCTGCGCTGCATAGGTCGGCGCATGCGCGCCTATGAGAAACAAGAAAATCGGGTTTCTGTGCAACAGCTTGATTGATGTACGGCCCCTACGCTTATGGAGCATCATCGCGAGCCAAATCAATATCACGGGAATACGATACGGTACGACCA",
                "GCGGCTACGTATTCTGTCGGAGTAGCGGCCGTCTGCCCAGACGACCTATAGAAAGCGGCGGACAGGCTGAGCGAGGTACTACTTCTACAAATACTGTCGATGGTAATCTCCTACCGCACGGCGTCTAAAGCATGGTAAAGAAAATCTCTAGTCTCTGATTCAGCATCTGTGCCGTGTATTAGAACCGTGGGGCCCCCGGAGGTTTCATACCAGTTCGACTATCCGAGATGATCTCCATATCGTCTAATACACTCATCTAGACAGTGCCATAGTGAAAATAGACTAACGGCCCGCCCTTGA",
                "AGCAAGAATTGCCATCCCCCTCTTGCCACACTCACATTATTGGATGTCTACGGACATGATAAATTCGCTCCTATCAATGTACTCCATATGTCTAGACATTATCGGTTGTGAGATTCGGACCCCCACCCGATTGGGTATAGAGAGTATTATATTAGTCGGACTCCGCATTAATATCTCGTGTATAGTGTACCGGTCTATGCGCTTGGGGGGTGATACTCGATTGCGCATTGTTGGAAACTGCCAACTAGAATAGATTTACTTCTACATATTCTGGGCAGCTTGGGGTCTTAGGTCCGAATG",
                "CCTGGGTTGATGTATAATTTTAGTACGGGAGACGTGTGTGTTCGCGCCGCAAGAAGGTCTCTGCAAAAAACCTGTCTCTTCTACACACTGGAAAGTGAAGGGTGAGCGGCGGACATAGGTGTGTCTTGCCTATACGACAGGCGGTTTTGGAACATGCGGCCCCATGTAGCCTGGCCCACAGCCTTTAAAATGGCTTAGCAAAAATGGTACGGCCCTGCCTGAAGTTCGGAGGAGTACCGCCGGGTCGATTTGTGATGTGGTTTCGGGTGTACTTGTGTCAATTGGATTCCGCGAAACCCA"
                };


    char model[] = "ATAGT";
    Noeud * arbre = nouveauNoeud();
    int s = 0;

    for (s; s != 5; s++){
        printf("[DEBUG] S: %d\n",s);
        for(int i = 0; i < 295; i++) // gestion de la fin du tab
        {
            ajouteMotArbre(arbre,seq[s]+i,0,i,s); // seq et seq + i
        }
    }
    Noeud * bob = chercheMotArbre(arbre,model,0);
    printf("[DEBUG] J'ai mon noeud\n");
    afficheLC(bob->cell);
    getAllFeuilles(arbre); // fonction qui vérifie les tablflag de toutes les feuilles, pas encore testé


    return 0;
}